### ISSUE TITLE
POST didn't work

### ISSUE THREAD

**Issue by shufps** [coffeepenbit/bookstack#1]
I think, this is wrong:

https://github.com/coffeepenbit/bookstack/blob/ac63b0ef0c67bff39a8abafe1c09f7345a65d616/src/bookstack/models.py#L50

POST didn't work because **kwargs was not passed to the requests function. Therefore, it was not possible to use the `data` parameter.

```python
            response = self._session.request(
                method_info['method'],
                #method_info['uri'].format(**kwargs)       <- this didn't work for POST
                method_info['uri'],
                **kwargs
            )
```

**Comment by shufps** [comment]
Closing the issue because of the PR

**Comment by coffeepenbit** [comment]
Thanks, I merged it
