### ISSUE TITLE
add minimal sample for post request

### ISSUE THREAD

**Issue by eckad158** [coffeepenbit/bookstack#3]
hi, first of all i am a total python newbee and i am trying to use your bookstack api.
the connection works and the api element shows me all the allowed api methods.
however i am not able to perform a post request.

is it somehow possible to add a minimal sample how to perform a post request using a simple json payload ? 
That would be awesome. Thanks

**Comment by coffeepenbit** [comment]
This may help:

> BookStack has a built-in REST API for external interaction and consumption of your BookStack data. API documentation can be found within your BookStack instance at the /api/docs URL path. You’ll need to have the ‘Access system API’ role permission to access the API or view the API documentation page.

From https://www.bookstackapp.com/docs/admin/hacking-bookstack/ , under the "BookStack API" heading

**Comment by coffeepenbit** [comment]
Thanks @DerpyJakey
