### ISSUE TITLE
POST method argument error

### ISSUE THREAD

**Issue by GenTexX** [coffeepenbit/bookstack#7]
I cannot call any post methods.

Installed with PIP
Version: **0.1.0b0**

**Error:** TypeError: BookStack._create_api_method.<locals>.request_method() takes 0 positional arguments but 1 was given

I don't know if I am doing something wrong, but it happens, even if i call the method from the readme?!

**Comment by MakusuB** [comment]
Hi there,

same here. Exactly copied the example from readme, but got the same error as @GenTexX. I am using Python 3.10. 

I am currently trying to fix it myself, but I'm still a beginner in Python.

**Comment by coffeepenbit** [comment]
I no longer use bookstack, but if you resolve the issue I will approve your pull request(s)

**Comment by MakusuB** [comment]
found the problem: the git code works absolutely fine, but the python package itself has not been updated yet. the additions by Jacob Stevens are not included there. would you be so kind and update it @coffeepenbit? that would be great!

**Comment by coffeepenbit** [comment]
If i can find time I will do it.

Thanks notifying me.

**Comment by gbouthenot** [comment]
pip still has the outdated "0.1.0b0" version : https://pypi.org/project/bookstack/
Please upgrade !

After upgrading to master:
```python
api.post_books_create({'name': 'Sample Book', 'description': 'Sample Description', 'tags': [{ 'name': 'Sample-Name', 'value': 'Sample-Value' }] })
{'error': {'message': 'The given data was invalid.', 'validation': {'name': ['The name field is required.']}, 'code': 422}}
```

I give up.

**Comment by coffeepenbit** [comment]
Closing with PR #10 ; let me know if you run into anything
